#+title: embark-vc 🚀
#+author: Ellis Kenyő
#+date: 2021-11-21
#+latex_class: chameleon

[[https://melpa.org/#/embark-vc][file:https://melpa.org/packages/embark-vc-badge.svg]]

Some glue between embark and a number of version control packages. As it's
(currently) quite simple, there's not much to document. /As that changes, so
will this/.

Currently provides targets and actions for:
- Magit (forge)
- smerge-mode
- code-review

All of which are considered dependencies, but as the package grows they will
become optional (if I did that now, it wouldn't do anything!)

* Terminology
In the context of Magit, Issues and Pull Requests are both marked as "topics",
and are referred to as such in the codebase to denote actions that apply to
both. For example, setting the title of an Issue or a Pull Request is
fundamentally the same operation, however Issues can't be merged.

So the "topic" actions are defined as actions that would apply to both Issues
and Pull Requests, with both also having their own set of actions to act on.

* Install
** Standard
Clone the repo, add to your load-path
** MELPA
Install using your favourite package manager
** Doom Emacs
Append the following to the corresponding file:

*** =packages.el=
#+begin_src emacs-lisp
(package! embark-vc)
#+end_src

*** =config.el=
#+begin_src emacs-lisp
(use-package! embark-vc
  :after embark)
#+end_src

* Keymaps
Currently all it really does is create some targets and add some wrapped
verisons of existing functions.

** =topic=
Keymap applies to both Pull Requests and Issues, so won't be duplicated there

| key | action                          |
|-----+---------------------------------|
| =y=   | =forge-copy-url-at-point-as-kill= |
| =s=   | =embark-vc-edit-topic-state=      |
| =t=   | =embark-vc-edit-topic-title=      |
| =l=   | =embark-vc-edit-topic-labels=     |

** =pull-request=
Only list actions that are relevant to just Pull Requests

| key | action                    |
|-----+---------------------------|
| =b=   | =embark-vc-checkout-branch= |
| =r=   | =embark-vc-start-review=    |
| =n=   | =forge-merge=               |

** =issue=
Only list actions that are relevant to just Issues

| key | action |
|-----+--------|

** =commit=
Only list actions that are relevant to Commits

| key | action              |
|-----+---------------------|
| =b=   | =forge-browse-commit= |

** =conflict=
Only list actions that are relevant to Merge Conflicts

| key | action            |
|-----+-------------------|
| =t=   | =smerge-keep-upper= |
| =b=   | =smerge-keep-lower= |
| =a=   | =smerge-keep-all=   |
| =d=   | =smerge-ediff=      |
